name: gisela
favicon: null
layout_spectrum: 0.661396661773324
typography_spectrum: 0.8174459054134786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3358413621317595
  lightness: 0.8620942989364266
  saturation: 0.08366244472563267
  rhythmicContrast: 0.75273631606251
purpose: []
